blank_issues_enabled: true
contact_links:
  - name: Engineering Stores Instagram
    url: https://www.instagram.com/uoftengstores//
    about: Follow our Instagram for news and updates about the Engineering Stores.
