blank_issues_enabled: true
contact_links:
  - name: Engineering Stores Instagram
    url: https://www.instagram.com/uoftengstores//
    about: DM us on Instagram to let us know about issues you are experiencing.
